version: "3"
services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST} #https://stackoverflow.com/questions/33357567/econnrefused-for-postgres-on-nodejs-with-dockers
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "1337:1337"
    volumes:
      - ./api/config:/opt/app/config
      - ./api/src:/opt/app/src
      - ./api/package.json:/opt/package.json
      - ./api/package-lock.json:/opt/package-lock.json # Replace with package-lock.json if using npm
      - .env:/opt/app/.env
    networks:
      - proxy
      - default
    depends_on:
      - db

  db:
    image: postgres:14.0-alpine
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  cloudbeaver:
    image: dbeaver/cloudbeaver
    restart: always
    volumes:
      - cloudbeaverData:/opt/cloudbeaver/
    ports:
      - "8080:8978"
    networks:
      - proxy
      - default

  app:
    build:
      context: ./app
      dockerfile: Dockerfile-dev
    volumes:
      - ./app/:/usr/src/app
    ports:
      - "4200:4200"
    networks:
      - proxy
      - default

volumes:
  data:
  cloudbeaverData:

networks:
  proxy:

