#version: "3.3"
#services:
#
##  nginx-proxy:
##    image: jwilder/nginx-proxy
##    restart: always
##    ports:
##      - "80:80"
##      - "443:443"
##    volumes:
##      - /var/run/docker.sock:/tmp/docker.sock:ro
##      - certs:/etc/nginx/certs:ro
##      - vhostd:/etc/nginx/vhost.d
##      - html:/usr/share/nginx/html
##    labels:
##      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
##    networks:
##      - strapi
##
##  letsencrypt:
##    image: nginxproxy/acme-companion
##    restart: always
##    environment:
##      - NGINX_PROXY_CONTAINER=nginx-proxy
##    volumes:
##      - certs:/etc/nginx/certs:rw
##      - vhostd:/etc/nginx/vhost.d
##      - html:/usr/share/nginx/html
##      - /var/run/docker.sock:/var/run/docker.sock:ro
##    networks:
##      - strapi
##
#  strapi:
#    container_name: webqube-starter-backend
#    build:
#      context: ./backend
#    #    image: webqube-starter-backend:latest
#    restart: unless-stopped
#    env_file: .env
#    environment:
#      DATABASE_CLIENT: ${DATABASE_CLIENT}
#      DATABASE_HOST: ${DATABASE_HOST}
#      DATABASE_NAME: ${DATABASE_NAME}
#      DATABASE_USERNAME: ${DATABASE_USERNAME}
#      DATABASE_PORT: ${DATABASE_PORT}
#      JWT_SECRET: ${JWT_SECRET}
#      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
#      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
#      NODE_ENV: ${NODE_ENV}
##      VIRTUAL_HOST: ${VIRTUAL_HOST}
##      VIRTUAL_PORT: ${VIRTUAL_PORT}
##      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
##      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
#    volumes:
#      - ./backend/config:/opt/app/config
#      - ./backend/src:/opt/app/src
#      - ./backend/package.json:/opt/package.json
#      - ./backend/package-lock.json:/opt/package-lock.json # Replace with package-lock.json if using npm
#      - ../.env:/opt/app/.env
#    expose:
#      - "1337"
#    networks:
#      - strapi
#    depends_on:
#      - postgres
##
#  postgres:
#    image: postgres:latest
#    container_name: strapiDB
#    #    platform: linux/arm64 #for platform error on Apple M1 chips
#    restart: unless-stopped
#    env_file: .env
#    environment:
#      POSTGRES_USER: ${DATABASE_USERNAME}
#      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
#      POSTGRES_DB: ${DATABASE_NAME}
#    volumes:
#      - strapi-data:/var/lib/postgresql/data/ #using a volume
#    ports:
#      - "5432:5432"
#    networks:
#      - strapi
#
#  dbAdmin:
#    container_name: pgadmin4_container
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "5050:80"
#    networks:
#      - strapi
#
#
#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: frontend/Dockerfile-dev
#    ports:
#      - "4200:4200"
##    environment:
##      VIRTUAL_HOST: webqube.de
##      VIRTUAL_PORT: '80'
##      LETSENCRYPT_HOST: webqube.de
##      LETSENCRYPT_EMAIL: admin@webqube.de
#    networks:
#      - strapi
#
##volumes:
##  certs:
##  vhostd:
##  html:
##  strapi-data:
#
#networks:
#  strapi:
#    driver: bridge
