version: "3"
services:

  api:
    image: webqube/starter-api
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST} #https://stackoverflow.com/questions/33357567/econnrefused-for-postgres-on-nodejs-with-dockers
      DATABASE_NAME: ${DATABASE_NAME}-${SUBDOMAIN}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${SUBDOMAIN}-api-secure.entrypoints=websecure"
      - "traefik.http.routers.${SUBDOMAIN}-api-secure.rule=Host(`${SUBDOMAINAPI}.${ROOT_URL}`)"
    networks:
      - proxy
      - default
    depends_on:
      - db

  db:
    image: postgres:14.0-alpine
    restart: unless-stopped
    networks:
      - proxy
      - default
    environment:
      POSTGRES_DB: ${DATABASE_NAME}-${SUBDOMAIN}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data/ #using a volume


  web:
    image: webqube/starter-web
    restart: unless-stopped
    env_file: .env
#    environment:
#      DATABASE_CLIENT: ${DATABASE_CLIENT}
#      DATABASE_HOST: ${DATABASE_HOST} #https://stackoverflow.com/questions/33357567/econnrefused-for-postgres-on-nodejs-with-dockers
#      DATABASE_NAME: ${DATABASE_NAME}-${SUBDOMAIN}
#      DATABASE_USERNAME: ${DATABASE_USERNAME}
#      DATABASE_PORT: ${DATABASE_PORT}
#      JWT_SECRET: ${JWT_SECRET}
#      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
#      NODE_ENV: ${NODE_ENV}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${SUBDOMAIN}-api-secure.entrypoints=websecure"
      - "traefik.http.routers.${SUBDOMAIN}-api-secure.rule=Host(`${SUBDOMAINWEB}.${ROOT_URL}`)"
#    build:
#      context: ./web
#      dockerfile: Dockerfile-prod
#    volumes:
#      - ./web/:/usr/src/app
    networks:
      - proxy
      - default



volumes:
  data:

networks:
  proxy:
    external: true
